// MongoDB User Schema Structure
export const UserModel = {
  // GitHub Data (fetched automatically)
  githubId: String, // GitHub user ID
  githubUsername: String, // GitHub username for portfolio URL
  githubData: {
    name: String,
    bio: String,
    avatar_url: String,
    html_url: String,
    blog: String, // website URL
    location: String,
    email: String,
    hireable: Boolean,
    public_repos: Number,
    public_gists: Number,
    followers: Number,
    following: Number,
    created_at: Date,
    updated_at: Date,
    company: String,
    twitter_username: String,
  },

  // Generated Content
  aiGeneratedDescription: String, // Generated by Gemini API

  // User Form Data (from form submission)
  personalInfo: {
    displayName: String,
    title: String, // e.g., "Full Stack Developer"
    customBio: String,
    phone: String,
    linkedin: String,
    portfolio: String,
    resume: String, // URL to resume
  },

  // Technical Skills
  techStack: {
    languages: [String], // ["JavaScript", "Python", "TypeScript"]
    frameworks: [String], // ["React", "Node.js", "Express"]
    tools: [String], // ["Git", "Docker", "AWS"]
    databases: [String], // ["MongoDB", "PostgreSQL"]
  },

  // Professional Experience
  workExperience: [
    {
      company: String,
      position: String,
      startDate: Date,
      endDate: Date, // null if current
      description: String,
      technologies: [String],
      isCurrent: Boolean,
    },
  ],

  // Education
  education: [
    {
      institution: String,
      degree: String,
      field: String,
      startDate: Date,
      endDate: Date,
      gpa: String,
      description: String,
    },
  ],

  // Projects (can be fetched from GitHub + manual additions)
  projects: [
    {
      name: String,
      description: String,
      technologies: [String],
      githubUrl: String,
      liveUrl: String,
      imageUrl: String,
      featured: Boolean,
      isGithubRepo: Boolean,
    },
  ],

  // Portfolio Settings
  portfolioSettings: {
    theme: String, // "dark", "light", "colorful"
    primaryColor: String,
    isPublic: Boolean,
    customDomain: String,
    seoTitle: String,
    seoDescription: String,
  },

  // GitHub Analytics (fetched periodically)
  githubStats: {
    contributionData: Object, // GitHub contribution graph data
    topLanguages: Object, // Language statistics
    mostStarredRepos: [Object],
    recentActivity: [Object],
    lastUpdated: Date,
  },

  // Metadata
  createdAt: Date,
  updatedAt: Date,
  lastLogin: Date,
  portfolioViews: Number,
};
